name: Check Copyright Boilerplate

on:
  pull_request:
    paths:
      - '**/*'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_RUN_ID: ${{ github.run_id }}
  GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  check:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check Copyright Boilerplate
      run: .github/scripts/check_boilerplate.sh
