# SPDX-FileCopyrightText: 2023 bootloose authors
# SPDX-License-Identifier: Apache-2.0

name: Publish Images

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - 'images/**/Dockerfile'
  workflow_dispatch:
    inputs:
      tag:
        description: The tag to use for images. Defaults to the tag name if publishing a tag, "latest" otherwise.
        required: false

jobs:
  prepare:
    runs-on: ubuntu-22.04
    outputs:
      tag: ${{ steps.set-tag.outputs.tag }}
      images: ${{ steps.list-images.outputs.images }}
    steps:
      - name: Set tag
        id: set-tag
        env:
          TAG: "${{ inputs.tag }}"
        run: |
          if [ -z "$TAG" ] && [[ "$GITHUB_REF" = refs/tags/* ]]; then
            TAG="${GITHUB_REF#refs/tags/}"
          fi
          echo tag="${TAG-latest}" >>"$GITHUB_OUTPUT"

      - name: List images
        id: list-images
        env:
          BEFORE: "${{ github.event.before }}"
        run: |
          if [ "$GITHUB_EVENT_NAME" = workflow_dispatch ] || [[ "$GITHUB_REF" = refs/tags/* ]]; then
            gh api /repos/{owner}/{repo}/git/trees/"${GITHUB_SHA}"?recursive=1 --paginate --jq '
              [ .tree[]
                | select(.type == "blob")
                | .path
                | split("/")
                | select(length == 3 and .[0] == "images" and .[2] == "Dockerfile")
                | .[1]
              ] | unique | "images=" + tojson
            ' >>"$GITHUB_OUTPUT"
          else
            gh api /repos/{owner}/{repo}/compare/"${BEFORE}...${GITHUB_SHA}" --paginate --jq '
              [ .files[].filename
                | split("/")
                | select(length == 3 and .[0] == "images" and .[2] == "Dockerfile")
                | .[1]
              ] | unique | "images=" + tojson
            ' >>"$GITHUB_OUTPUT"
          fi

  publish_images:
    needs: prepare
    strategy:
      matrix:
        image: ${{fromJson(needs.prepare.outputs.images)}}
      fail-fast: false

    uses: ./.github/workflows/publish-image.yaml
    with:
      image: ${{ matrix.image }}
      tag: ${{ needs.prepare.outputs.tag }}
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
