name: Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  prepare:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.list-arch.outputs.matrix_image_platforms }}
      tag: ${{ steps.tag-name.outputs.tag }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Tag name
      id: tag-name
      run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
    - name: List images and architecture support
      id: list-arch
      run: |
        echo "matrix_image_platforms=$(./image-platform-matrix-json.sh)" >> $GITHUB_OUTPUT

  publish_images:
    if: startsWith(github.ref, 'refs/tags/')
    needs: prepare
    runs-on: ubuntu-20.04
    strategy:
      matrix: ${{fromJson(needs.prepare.outputs.matrix)}}
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Login to Quay
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.QUAY_USER }}
        password: ${{ secrets.QUAY_PASSWORD }}
        registry: quay.io

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Buildx Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx

    - name: Build ${{ matrix.image }}
      uses: docker/build-push-action@v5
      with:
        platforms: ${{ matrix.platforms }}
        load: true
        push: true
        tags: |
          quay.io/k0sproject/footloose-${{ matrix.image }}:latest
          quay.io/k0sproject/footloose-${{ matrix.image }}:${{ needs.prepare.outputs.tag }}
        context: images/${{ matrix.image }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

    - name: Tag and Push :latest
      if: ${{ !contains(needs.prepare.outputs.tag, '-') }}
      run: |
        docker tag quay.io/k0sproject/footloose-${{ matrix.image }}:${{ needs.prepare.outputs.tag }} quay.io/k0sproject/footloose-${{ matrix.image }}:latest
        docker push quay.io/k0sproject/footloose-${{ matrix.image }}:latest
    
  publish_binaries:
    if: startsWith(github.ref, 'refs/tags/')
    name: release
    needs: prepare
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Build binaries
        id: build_bins
        env:
          TAG_NAME: ${{ needs.prepare.outputs.tag }}
        run: make build-all

      - name: Create release and upload binaries
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/footloose-*
            bin/sha256sums.txt
          body_path: bin/checksums.md
          tag_name: ${{ needs.prepare.outputs.tag }}
          name: ${{ needs.prepare.outputs.tag }}
          draft: true # So we can manually edit before publishing
          prerelease: ${{ contains(needs.prepare.outputs.tag, '-') }} # v0.1.2-beta1, 1.2.3-rc1
